# Generated by Django 4.1.7 on 2023-04-05 22:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_task_condition_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='longread',
            name='longread_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='unit_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('level', models.IntegerField()),
                ('unit_id', models.IntegerField()),
                ('longread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='courses.longread')),
            ],
        ),
    ]
