# Generated by Django 4.1.7 on 2023-04-05 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_longread_longread_id_task_level_task_unit_id_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
