# Generated by Django 4.1.7 on 2023-04-15 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_task_trueanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='levels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('longread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='courses.longread')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='courses.student')),
            ],
        ),
    ]
